#imprime los datos de la autora
print("JIMENEZ GAMBOA ISSIS ALEXA")
print("no.1189")
print("3W")
#imprime una linea en blanco 
print("")

import math

import math  #Importa el módulo math para operaciones matemáticas
from typing import List, Tuple, Union  #Importa tipos para anotaciones de tipo

# 1. Función que muestra el saludo "Hey amigos!"
def saludo_general() -> str:
    return "Hey amigos!"  #Retorna el saludo general
#Ejemplos de uso
print(saludo_general())  #Imprime el saludo general