#imprime los datos de la autora
print("JIMENEZ GAMBOA ISSIS ALEXA")
print("no.1189")
print("3W")
#imprime una linea en blanco 
print("")

#9.Funciones para sumar y multiplicar números de una lista
def sum(lista):
    return sum(lista)

def multip(lista):
    resultado = 1
    for num in lista:
        resultado *= num
    return resultado
#Ejemplo de uso 
print(sum([1, 2, 3, 4]))  #Imprime la suma de una lista de números
print(multip([1, 2, 3, 4]))  #Imprime el producto de una lista de números